### ISSUE TITLE
Remove BigInt Support or add BigInt.range as another function

### ISSUE THREAD

**Issue by tiansh** [Jack-Works/proposal-Number.range#4]
Currently, it test if `from` and `to` against type `bigint`. I would suggest to remove the `bigint` support in `Number.range`. If you really want to support it, add another `BigInt.range` should be reasonable. So we can make `Number.range` do exactly what it describe.

**Comment by Jack-Works** [comment]
Sound reasonable. wait for more community discussion.

**Comment by obedm503** [comment]
This makes sense since Number and BigInt are not the same type. Also, it makes range more explicit. It resolves the issue of figuring out what to do when the types don't match

**Comment by Jack-Works** [comment]
Merged into the spec.

**Comment by Jack-Works** [comment]
Removed feature flag. This becomes the default behavior now.
