### ISSUE TITLE
Verify isFinite on `from` and `step`

### ISSUE THREAD

**Issue by tiansh** [Jack-Works/proposal-Number.range#6]
`from` and `step` should be `isFinite` since you cannot have `Number.range(-Infinity, Infinity)`.

Use `Infinity` for `to` should be some how reasonable. But it may not work correctly in most cases due to floating point errors.

**Comment by Jack-Works** [comment]
Yes, but what should we do when involve `from` or `step` is `Infinity`?

- Throws?
- Do we have other choices...?

**Comment by tiansh** [comment]
Throw `RangeError` should be the best idea imo.

**Comment by Jack-Works** [comment]
Closed by https://github.com/Jack-Works/proposal-Number.range/commit/1e4adb48cf5c197f375a6ba03758f1e24d4afe49
